//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbakonXVWPF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pl-PL")]
        public string _Language {
            get {
                return ((string)(this["_Language"]));
            }
            set {
                this["_Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Undefined")]
        public string _DB_server {
            get {
                return ((string)(this["_DB_server"]));
            }
            set {
                this["_DB_server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Undefined")]
        public string _DB_user {
            get {
                return ((string)(this["_DB_user"]));
            }
            set {
                this["_DB_user"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Undefined")]
        public string _DB_Name {
            get {
                return ((string)(this["_DB_Name"]));
            }
            set {
                this["_DB_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _DB_Authetification {
            get {
                return ((bool)(this["_DB_Authetification"]));
            }
            set {
                this["_DB_Authetification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5433")]
        public string _Port {
            get {
                return ((string)(this["_Port"]));
            }
            set {
                this["_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _DB_psw {
            get {
                return ((string)(this["_DB_psw"]));
            }
            set {
                this["_DB_psw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _partnerId_DGHeader {
            get {
                return ((string)(this["_partnerId_DGHeader"]));
            }
            set {
                this["_partnerId_DGHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _partnerCode_DGHeader {
            get {
                return ((string)(this["_partnerCode_DGHeader"]));
            }
            set {
                this["_partnerCode_DGHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PathToPatterns {
            get {
                return ((int)(this["PathToPatterns"]));
            }
            set {
                this["PathToPatterns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PathToDocuments_CollectionOfEquipment {
            get {
                return ((int)(this["PathToDocuments_CollectionOfEquipment"]));
            }
            set {
                this["PathToDocuments_CollectionOfEquipment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSelectedPattern_SingleEquipment {
            get {
                return ((string)(this["LastSelectedPattern_SingleEquipment"]));
            }
            set {
                this["LastSelectedPattern_SingleEquipment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSelectedPattern_CollectionOfEquipment {
            get {
                return ((string)(this["LastSelectedPattern_CollectionOfEquipment"]));
            }
            set {
                this["LastSelectedPattern_CollectionOfEquipment"] = value;
            }
        }
    }
}
