//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbakonData.LangKeys {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AbakonData.LangKeys.ResourceLang", typeof(ResourceLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string _admin {
            get {
                return ResourceManager.GetString("_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator privilege.
        /// </summary>
        internal static string _adminComment {
            get {
                return ResourceManager.GetString("_adminComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right task allocation.
        /// </summary>
        internal static string _allEquipmnetAccess {
            get {
                return ResourceManager.GetString("_allEquipmnetAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppUser.
        /// </summary>
        internal static string _appUser {
            get {
                return ResourceManager.GetString("_appUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid user of application.
        /// </summary>
        internal static string _appUserComment {
            get {
                return ResourceManager.GetString("_appUserComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The right to register new devices.
        /// </summary>
        internal static string _canAddEquipment {
            get {
                return ResourceManager.GetString("_canAddEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The right to register new partners.
        /// </summary>
        internal static string _canAddPartner {
            get {
                return ResourceManager.GetString("_canAddPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The right to register new persons.
        /// </summary>
        internal static string _canAddPerson {
            get {
                return ResourceManager.GetString("_canAddPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The right to remove devices from the database.
        /// </summary>
        internal static string _canDeleteEquipment {
            get {
                return ResourceManager.GetString("_canDeleteEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The right to remove partners from the database.
        /// </summary>
        internal static string _canDeletePartner {
            get {
                return ResourceManager.GetString("_canDeletePartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The right to remove persons from the database.
        /// </summary>
        internal static string _canDeletePerson {
            get {
                return ResourceManager.GetString("_canDeletePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The right to dispose devices to empoloyee.
        /// </summary>
        internal static string _canDisposeEquipmentToEmployee {
            get {
                return ResourceManager.GetString("_canDisposeEquipmentToEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The right to update data of devices.
        /// </summary>
        internal static string _canUpdateEquipment {
            get {
                return ResourceManager.GetString("_canUpdateEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The right to update data of partners.
        /// </summary>
        internal static string _canUpdatePartner {
            get {
                return ResourceManager.GetString("_canUpdatePartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The right to update data of persons.
        /// </summary>
        internal static string _canUpdatePerson {
            get {
                return ResourceManager.GetString("_canUpdatePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesure equipment.
        /// </summary>
        internal static string _equipmentHeader {
            get {
                return ResourceManager.GetString("_equipmentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a unit of measurement.
        /// </summary>
        internal static string _errForeingKeyProductMesureUnitCode {
            get {
                return ResourceManager.GetString("_errForeingKeyProductMesureUnitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a technical unit of measurement.
        /// </summary>
        internal static string _errForeingKeyProductTechnicalMesureUnitCode {
            get {
                return ResourceManager.GetString("_errForeingKeyProductTechnicalMesureUnitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a VAT rate.
        /// </summary>
        internal static string _errForeingKeyVATrateCodeId {
            get {
                return ResourceManager.GetString("_errForeingKeyVATrateCodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit is 12 characters.
        /// </summary>
        internal static string _errMaxLegth12 {
            get {
                return ResourceManager.GetString("_errMaxLegth12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit is 256 characters.
        /// </summary>
        internal static string _errMaxLegth256 {
            get {
                return ResourceManager.GetString("_errMaxLegth256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit is 30characters.
        /// </summary>
        internal static string _errMaxLegth30 {
            get {
                return ResourceManager.GetString("_errMaxLegth30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit is 60 characters.
        /// </summary>
        internal static string _errMaxLegth60 {
            get {
                return ResourceManager.GetString("_errMaxLegth60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit is 90 characters.
        /// </summary>
        internal static string _errMaxLegth90 {
            get {
                return ResourceManager.GetString("_errMaxLegth90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text can not be blank.
        /// </summary>
        internal static string _errMinLegth1 {
            get {
                return ResourceManager.GetString("_errMinLegth1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum length is 3 characters.
        /// </summary>
        internal static string _errMinLegth3 {
            get {
                return ResourceManager.GetString("_errMinLegth3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number must be in the range 1 to 1000.
        /// </summary>
        internal static string _errRange1To1000 {
            get {
                return ResourceManager.GetString("_errRange1To1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It must be a two-letter initials (in capitals without nationals characters).
        /// </summary>
        internal static string _errRegexInitialsNoMatched {
            get {
                return ResourceManager.GetString("_errRegexInitialsNoMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code does not match the pattern.
        /// </summary>
        internal static string _errRegexNoMatched {
            get {
                return ResourceManager.GetString("_errRegexNoMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partners.
        /// </summary>
        internal static string _partnerHeader {
            get {
                return ResourceManager.GetString("_partnerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People (representatives,  employees).
        /// </summary>
        internal static string _personHeader {
            get {
                return ResourceManager.GetString("_personHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string _roleAmin {
            get {
                return ResourceManager.GetString("_roleAmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal user.
        /// </summary>
        internal static string _roleUser {
            get {
                return ResourceManager.GetString("_roleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accepted contractors.
        /// </summary>
        internal static string acceptedContractors {
            get {
                return ResourceManager.GetString("acceptedContractors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afforded certificate.
        /// </summary>
        internal static string affordedCertificate {
            get {
                return ResourceManager.GetString("affordedCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered.
        /// </summary>
        internal static string delivered {
            get {
                return ResourceManager.GetString("delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depending on the circumstances.
        /// </summary>
        internal static string DoDecyzji {
            get {
                return ResourceManager.GetString("DoDecyzji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric.
        /// </summary>
        internal static string Elektryczne {
            get {
                return ResourceManager.GetString("Elektryczne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string finished {
            get {
                return ResourceManager.GetString("finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legalization of their own.
        /// </summary>
        internal static string LegalizacjaWlasna {
            get {
                return ResourceManager.GetString("LegalizacjaWlasna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mech..
        /// </summary>
        internal static string Mechaniczne {
            get {
                return ResourceManager.GetString("Mechaniczne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not subject to legalization.
        /// </summary>
        internal static string NiePodlegaLegalizacji {
            get {
                return ResourceManager.GetString("NiePodlegaLegalizacji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained after calibration.
        /// </summary>
        internal static string obtainedAfterCalibration {
            get {
                return ResourceManager.GetString("obtainedAfterCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed.
        /// </summary>
        internal static string proceed {
            get {
                return ResourceManager.GetString("proceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indefinite.
        /// </summary>
        internal static string PrzyrzadyWszystkie {
            get {
                return ResourceManager.GetString("PrzyrzadyWszystkie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redy to receive.
        /// </summary>
        internal static string redyToReceive {
            get {
                return ResourceManager.GetString("redyToReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeking a broker.
        /// </summary>
        internal static string seekingBroker {
            get {
                return ResourceManager.GetString("seekingBroker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeking a lab.
        /// </summary>
        internal static string seekingLab {
            get {
                return ResourceManager.GetString("seekingLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent the equipment.
        /// </summary>
        internal static string sentEquipment {
            get {
                return ResourceManager.GetString("sentEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sent request.
        /// </summary>
        internal static string sentRequest {
            get {
                return ResourceManager.GetString("sentRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gauge.
        /// </summary>
        internal static string Sprawdziany {
            get {
                return ResourceManager.GetString("Sprawdziany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For threads.
        /// </summary>
        internal static string SprawdzianyDoGwintow {
            get {
                return ResourceManager.GetString("SprawdzianyDoGwintow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start process.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not subject to verification.
        /// </summary>
        internal static string ZawszeZlecana {
            get {
                return ResourceManager.GetString("ZawszeZlecana", resourceCulture);
            }
        }
    }
}
